# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Body5(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: int=None, username: str=None, first_name: str=None, last_name: str=None, email: str=None, password: str=None, phone: str=None, user_status: int=None):
        """
        Body5 - a model defined in Swagger

        :param id: The id of this Body5.
        :type id: int
        :param username: The username of this Body5.
        :type username: str
        :param first_name: The first_name of this Body5.
        :type first_name: str
        :param last_name: The last_name of this Body5.
        :type last_name: str
        :param email: The email of this Body5.
        :type email: str
        :param password: The password of this Body5.
        :type password: str
        :param phone: The phone of this Body5.
        :type phone: str
        :param user_status: The user_status of this Body5.
        :type user_status: int
        """
        self.swagger_types = {
            'id': int,
            'username': str,
            'first_name': str,
            'last_name': str,
            'email': str,
            'password': str,
            'phone': str,
            'user_status': int
        }

        self.attribute_map = {
            'id': 'id',
            'username': 'username',
            'first_name': 'firstName',
            'last_name': 'lastName',
            'email': 'email',
            'password': 'password',
            'phone': 'phone',
            'user_status': 'userStatus'
        }

        self._id = id
        self._username = username
        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._password = password
        self._phone = phone
        self._user_status = user_status

    @classmethod
    def from_dict(cls, dikt) -> 'Body5':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_5 of this Body5.
        :rtype: Body5
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """
        Gets the id of this Body5.

        :return: The id of this Body5.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """
        Sets the id of this Body5.

        :param id: The id of this Body5.
        :type id: int
        """

        self._id = id

    @property
    def username(self) -> str:
        """
        Gets the username of this Body5.

        :return: The username of this Body5.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """
        Sets the username of this Body5.

        :param username: The username of this Body5.
        :type username: str
        """

        self._username = username

    @property
    def first_name(self) -> str:
        """
        Gets the first_name of this Body5.

        :return: The first_name of this Body5.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """
        Sets the first_name of this Body5.

        :param first_name: The first_name of this Body5.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """
        Gets the last_name of this Body5.

        :return: The last_name of this Body5.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """
        Sets the last_name of this Body5.

        :param last_name: The last_name of this Body5.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def email(self) -> str:
        """
        Gets the email of this Body5.

        :return: The email of this Body5.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """
        Sets the email of this Body5.

        :param email: The email of this Body5.
        :type email: str
        """

        self._email = email

    @property
    def password(self) -> str:
        """
        Gets the password of this Body5.

        :return: The password of this Body5.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """
        Sets the password of this Body5.

        :param password: The password of this Body5.
        :type password: str
        """

        self._password = password

    @property
    def phone(self) -> str:
        """
        Gets the phone of this Body5.

        :return: The phone of this Body5.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """
        Sets the phone of this Body5.

        :param phone: The phone of this Body5.
        :type phone: str
        """

        self._phone = phone

    @property
    def user_status(self) -> int:
        """
        Gets the user_status of this Body5.
        User Status

        :return: The user_status of this Body5.
        :rtype: int
        """
        return self._user_status

    @user_status.setter
    def user_status(self, user_status: int):
        """
        Sets the user_status of this Body5.
        User Status

        :param user_status: The user_status of this Body5.
        :type user_status: int
        """

        self._user_status = user_status

