# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse2003(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: int=None, pet_id: int=None, quantity: int=None, ship_date: datetime=None, status: str=None, complete: bool=False):
        """
        InlineResponse2003 - a model defined in Swagger

        :param id: The id of this InlineResponse2003.
        :type id: int
        :param pet_id: The pet_id of this InlineResponse2003.
        :type pet_id: int
        :param quantity: The quantity of this InlineResponse2003.
        :type quantity: int
        :param ship_date: The ship_date of this InlineResponse2003.
        :type ship_date: datetime
        :param status: The status of this InlineResponse2003.
        :type status: str
        :param complete: The complete of this InlineResponse2003.
        :type complete: bool
        """
        self.swagger_types = {
            'id': int,
            'pet_id': int,
            'quantity': int,
            'ship_date': datetime,
            'status': str,
            'complete': bool
        }

        self.attribute_map = {
            'id': 'id',
            'pet_id': 'petId',
            'quantity': 'quantity',
            'ship_date': 'shipDate',
            'status': 'status',
            'complete': 'complete'
        }

        self._id = id
        self._pet_id = pet_id
        self._quantity = quantity
        self._ship_date = ship_date
        self._status = status
        self._complete = complete

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.
        :rtype: InlineResponse2003
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """
        Gets the id of this InlineResponse2003.

        :return: The id of this InlineResponse2003.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """
        Sets the id of this InlineResponse2003.

        :param id: The id of this InlineResponse2003.
        :type id: int
        """

        self._id = id

    @property
    def pet_id(self) -> int:
        """
        Gets the pet_id of this InlineResponse2003.

        :return: The pet_id of this InlineResponse2003.
        :rtype: int
        """
        return self._pet_id

    @pet_id.setter
    def pet_id(self, pet_id: int):
        """
        Sets the pet_id of this InlineResponse2003.

        :param pet_id: The pet_id of this InlineResponse2003.
        :type pet_id: int
        """

        self._pet_id = pet_id

    @property
    def quantity(self) -> int:
        """
        Gets the quantity of this InlineResponse2003.

        :return: The quantity of this InlineResponse2003.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """
        Sets the quantity of this InlineResponse2003.

        :param quantity: The quantity of this InlineResponse2003.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def ship_date(self) -> datetime:
        """
        Gets the ship_date of this InlineResponse2003.

        :return: The ship_date of this InlineResponse2003.
        :rtype: datetime
        """
        return self._ship_date

    @ship_date.setter
    def ship_date(self, ship_date: datetime):
        """
        Sets the ship_date of this InlineResponse2003.

        :param ship_date: The ship_date of this InlineResponse2003.
        :type ship_date: datetime
        """

        self._ship_date = ship_date

    @property
    def status(self) -> str:
        """
        Gets the status of this InlineResponse2003.
        Order Status

        :return: The status of this InlineResponse2003.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """
        Sets the status of this InlineResponse2003.
        Order Status

        :param status: The status of this InlineResponse2003.
        :type status: str
        """
        allowed_values = ["placed", "approved", "delivered"]
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def complete(self) -> bool:
        """
        Gets the complete of this InlineResponse2003.

        :return: The complete of this InlineResponse2003.
        :rtype: bool
        """
        return self._complete

    @complete.setter
    def complete(self, complete: bool):
        """
        Sets the complete of this InlineResponse2003.

        :param complete: The complete of this InlineResponse2003.
        :type complete: bool
        """

        self._complete = complete

